class NotificationDBO {
    constructor() {
    }

    mockNotifications = [
        {
            id: "1",
            source: "ORDER_SYSTEM",
            category: "ORDER",
            type: "USER",
            title: "Order has been shipped",
            message: "Your order #4567 has been shipped and is on the way!",
            code: "NOTIFICATION",
            data: { orderId: "4567" },
            url: "https://example.com/orders/4567",
            read: false,
            readAt: null,
            sent: true,
            deliveryChannels: ["PUSH", "EMAIL"],
            priority: "NORMAL",
            createdAt: "2025-06-08T10:30:00Z",
            updatedAt: "2025-06-08T10:30:00Z",
        },
        {
            id: "2",
            source: "ADMIN_PANEL",
            category: "ADMIN_ACTIONS",
            type: "ADMIN",
            title: "Account Suspended",
            message: "Your account has been suspended due to policy violations.",
            code: "USER_UPDATED",
            data: { reason: "Policy violation" },
            url: null,
            read: true,
            readAt: "2025-06-07T12:00:00Z",
            sent: true,
            deliveryChannels: ["IN_APP"],
            priority: "HIGH",
            createdAt: "2025-06-07T11:50:00Z",
            updatedAt: "2025-06-07T12:00:00Z",
        },
        {
            id: "3",
            source: "SYSTEM_ALERT",
            category: "SYSTEM",
            type: "SYSTEM",
            title: "System Downtime",
            message: "Scheduled maintenance on June 10, 2:00–4:00 AM UTC.",
            code: "NOTIFICATION",
            data: {},
            url: "https://status.example.com",
            read: false,
            readAt: null,
            sent: true,
            deliveryChannels: ["EMAIL", "IN_APP"],
            priority: "CRITICAL",
            createdAt: "2025-06-06T08:00:00Z",
            updatedAt: "2025-06-06T08:00:00Z",
        },
        {
            id: "4",
            source: "MARKETING",
            category: "PROMOTION",
            type: "PROMOTION",
            title: "Limited Offer: Free Shipping",
            message: "Enjoy free shipping on orders above $50 until June 15!",
            code: "NOTIFICATION",
            data: { promo: "FREESHIP" },
            url: "https://example.com/offers",
            read: true,
            readAt: "2025-06-05T15:20:00Z",
            sent: true,
            deliveryChannels: ["EMAIL"],
            priority: "INFO",
            createdAt: "2025-06-05T15:00:00Z",
            updatedAt: "2025-06-05T15:20:00Z",
        },
        {
            id: "5",
            source: "SECURITY_SYSTEM",
            category: "SECURITY",
            type: "SYSTEM",
            title: "New Login Detected",
            message: "A new login was detected from Chrome on Windows in Delhi, India.",
            code: "NOTIFICATION",
            data: { ip: "103.21.45.67", device: "Windows - Chrome" },
            url: null,
            read: false,
            readAt: null,
            sent: true,
            deliveryChannels: ["EMAIL", "PUSH"],
            priority: "CRITICAL",
            createdAt: "2025-06-04T19:40:00Z",
            updatedAt: "2025-06-04T19:40:00Z",
        },
        {
            id: "6",
            source: "SUPPORT_SYSTEM",
            category: "SUPPORT",
            type: "SUPPORT",
            title: "Ticket Resolved",
            message: "Your support ticket #98765 has been resolved. Please review it.",
            code: "NOTIFICATION",
            data: { ticketId: "98765" },
            url: "https://example.com/support/tickets/98765",
            read: true,
            readAt: "2025-06-03T09:00:00Z",
            sent: true,
            deliveryChannels: ["IN_APP"],
            priority: "NORMAL",
            createdAt: "2025-06-03T08:00:00Z",
            updatedAt: "2025-06-03T09:00:00Z",
        },
        {
            id: "7",
            source: "USER_CHAT",
            category: "CHAT",
            type: "USER",
            title: "New Message from Support",
            message: "Hi! Let us know if you need any more help with your issue.",
            code: "NOTIFICATION",
            data: { chatId: "abc123" },
            url: "https://example.com/chat/abc123",
            read: false,
            readAt: null,
            sent: true,
            deliveryChannels: ["IN_APP", "PUSH"],
            priority: "INFO",
            createdAt: "2025-06-02T13:30:00Z",
            updatedAt: "2025-06-02T13:30:00Z",
        },
        {
            id: "8",
            source: "ORDER_SYSTEM",
            category: "ORDER",
            type: "USER",
            title: "Order Shipped",
            message: "Your order #4567 has been shipped and is on the way!",
            code: "NOTIFICATION",
            data: { orderId: "4567" },
            url: "https://example.com/orders/4567",
            read: false,
            readAt: null,
            sent: true,
            deliveryChannels: ["PUSH", "EMAIL"],
            priority: "NORMAL",
            createdAt: "2025-06-08T10:30:00Z",
            updatedAt: "2025-06-08T10:30:00Z",
        },
        {
            id: "9",
            source: "ADMIN_PANEL",
            category: "ADMIN_ACTIONS",
            type: "ADMIN",
            title: "Account Suspended",
            message: "Your account has been suspended due to policy violations.",
            code: "USER_UPDATED",
            data: { reason: "Policy violation" },
            url: null,
            read: true,
            readAt: "2025-06-07T12:00:00Z",
            sent: true,
            deliveryChannels: ["IN_APP"],
            priority: "HIGH",
            createdAt: "2025-06-07T11:50:00Z",
            updatedAt: "2025-06-07T12:00:00Z",
        },
        {
            id: "3",
            source: "SYSTEM_ALERT",
            category: "SYSTEM",
            type: "SYSTEM",
            title: "System Downtime",
            message: "Scheduled maintenance on June 10, 2:00–4:00 AM UTC.",
            code: "NOTIFICATION",
            data: {},
            url: "https://status.example.com",
            read: false,
            readAt: null,
            sent: true,
            deliveryChannels: ["EMAIL", "IN_APP"],
            priority: "CRITICAL",
            createdAt: "2025-06-06T08:00:00Z",
            updatedAt: "2025-06-06T08:00:00Z",
        },
        {
            id: "4",
            source: "MARKETING",
            category: "PROMOTION",
            type: "PROMOTION",
            title: "Limited Offer: Free Shipping",
            message: "Enjoy free shipping on orders above $50 until June 15!",
            code: "NOTIFICATION",
            data: { promo: "FREESHIP" },
            url: "https://example.com/offers",
            read: true,
            readAt: "2025-06-05T15:20:00Z",
            sent: true,
            deliveryChannels: ["EMAIL"],
            priority: "INFO",
            createdAt: "2025-06-05T15:00:00Z",
            updatedAt: "2025-06-05T15:20:00Z",
        },
        {
            id: "5",
            source: "SECURITY_SYSTEM",
            category: "SECURITY",
            type: "SYSTEM",
            title: "New Login Detected",
            message: "A new login was detected from Chrome on Windows in Delhi, India.",
            code: "NOTIFICATION",
            data: { ip: "103.21.45.67", device: "Windows - Chrome" },
            url: null,
            read: false,
            readAt: null,
            sent: true,
            deliveryChannels: ["EMAIL", "PUSH"],
            priority: "CRITICAL",
            createdAt: "2025-06-04T19:40:00Z",
            updatedAt: "2025-06-04T19:40:00Z",
        },
        {
            id: "6",
            source: "SUPPORT_SYSTEM",
            category: "SUPPORT",
            type: "SUPPORT",
            title: "Ticket Resolved",
            message: "Your support ticket #98765 has been resolved. Please review it.",
            code: "NOTIFICATION",
            data: { ticketId: "98765" },
            url: "https://example.com/support/tickets/98765",
            read: true,
            readAt: "2025-06-03T09:00:00Z",
            sent: true,
            deliveryChannels: ["IN_APP"],
            priority: "NORMAL",
            createdAt: "2025-06-03T08:00:00Z",
            updatedAt: "2025-06-03T09:00:00Z",
        },
        {
            id: "7",
            source: "USER_CHAT",
            category: "CHAT",
            type: "USER",
            title: "New Message from Support",
            message: "Hi! Let us know if you need any more help with your issue.",
            code: "NOTIFICATION",
            data: { chatId: "abc123" },
            url: "https://example.com/chat/abc123",
            read: false,
            readAt: null,
            sent: true,
            deliveryChannels: ["IN_APP", "PUSH"],
            priority: "INFO",
            createdAt: "2025-06-02T13:30:00Z",
            updatedAt: "2025-06-02T13:30:00Z",
        },
        {
            id: "1",
            source: "ORDER_SYSTEM",
            category: "ORDER",
            type: "USER",
            title: "Order Shipped",
            message: "Your order #4567 has been shipped and is on the way!",
            code: "NOTIFICATION",
            data: { orderId: "4567" },
            url: "https://example.com/orders/4567",
            read: false,
            readAt: null,
            sent: true,
            deliveryChannels: ["PUSH", "EMAIL"],
            priority: "NORMAL",
            createdAt: "2025-06-08T10:30:00Z",
            updatedAt: "2025-06-08T10:30:00Z",
        },
        {
            id: "2",
            source: "ADMIN_PANEL",
            category: "ADMIN_ACTIONS",
            type: "ADMIN",
            title: "Account Suspended",
            message: "Your account has been suspended due to policy violations.",
            code: "USER_UPDATED",
            data: { reason: "Policy violation" },
            url: null,
            read: true,
            readAt: "2025-06-07T12:00:00Z",
            sent: true,
            deliveryChannels: ["IN_APP"],
            priority: "HIGH",
            createdAt: "2025-06-07T11:50:00Z",
            updatedAt: "2025-06-07T12:00:00Z",
        },
        {
            id: "3",
            source: "SYSTEM_ALERT",
            category: "SYSTEM",
            type: "SYSTEM",
            title: "System Downtime",
            message: "Scheduled maintenance on June 10, 2:00–4:00 AM UTC.",
            code: "NOTIFICATION",
            data: {},
            url: "https://status.example.com",
            read: false,
            readAt: null,
            sent: true,
            deliveryChannels: ["EMAIL", "IN_APP"],
            priority: "CRITICAL",
            createdAt: "2025-06-06T08:00:00Z",
            updatedAt: "2025-06-06T08:00:00Z",
        },
        {
            id: "4",
            source: "MARKETING",
            category: "PROMOTION",
            type: "PROMOTION",
            title: "Limited Offer: Free Shipping",
            message: "Enjoy free shipping on orders above $50 until June 15!",
            code: "NOTIFICATION",
            data: { promo: "FREESHIP" },
            url: "https://example.com/offers",
            read: true,
            readAt: "2025-06-05T15:20:00Z",
            sent: true,
            deliveryChannels: ["EMAIL"],
            priority: "INFO",
            createdAt: "2025-06-05T15:00:00Z",
            updatedAt: "2025-06-05T15:20:00Z",
        },
        {
            id: "5",
            source: "SECURITY_SYSTEM",
            category: "SECURITY",
            type: "SYSTEM",
            title: "New Login Detected",
            message: "A new login was detected from Chrome on Windows in Delhi, India.",
            code: "NOTIFICATION",
            data: { ip: "103.21.45.67", device: "Windows - Chrome" },
            url: null,
            read: false,
            readAt: null,
            sent: true,
            deliveryChannels: ["EMAIL", "PUSH"],
            priority: "CRITICAL",
            createdAt: "2025-06-04T19:40:00Z",
            updatedAt: "2025-06-04T19:40:00Z",
        },
        {
            id: "6",
            source: "SUPPORT_SYSTEM",
            category: "SUPPORT",
            type: "SUPPORT",
            title: "Ticket Resolved",
            message: "Your support ticket #98765 has been resolved. Please review it.",
            code: "NOTIFICATION",
            data: { ticketId: "98765" },
            url: "https://example.com/support/tickets/98765",
            read: true,
            readAt: "2025-06-03T09:00:00Z",
            sent: true,
            deliveryChannels: ["IN_APP"],
            priority: "NORMAL",
            createdAt: "2025-06-03T08:00:00Z",
            updatedAt: "2025-06-03T09:00:00Z",
        },
        {
            id: "7",
            source: "USER_CHAT",
            category: "CHAT",
            type: "USER",
            title: "New Message from Support",
            message: "Hi! Let us know if you need any more help with your issue.",
            code: "NOTIFICATION",
            data: { chatId: "abc123" },
            url: "https://example.com/chat/abc123",
            read: false,
            readAt: null,
            sent: true,
            deliveryChannels: ["IN_APP", "PUSH"],
            priority: "INFO",
            createdAt: "2025-06-02T13:30:00Z",
            updatedAt: "2025-06-02T13:30:00Z",
        },
    ];


    async list() {
        return this.mockNotifications.map((notification, index) => {
            return {
                ...notification,
                id: String(index + 1),
            }
        })
    }
}

export default new NotificationDBO();